### ISSUE TITLE
Fix false-positives for unknowns

### ISSUE THREAD

**Issue by maltfield** [frontendnetwork/Veganify-API#285]
## Bug description

Currently, if VeganCheck.me is given an ingredient that it doesn't recognize, it says that it is vegan -- even if it isn't

### Steps to reproduce 

1. Go to https://vegancheck.me/ingredients
2. Type "cow"
3. See message indicating that "cow" is vegan

### Solution

If a query for an ingredient that is submitted to VeganCheck is not known to VeganCheck's backend, then it should respond with an "I don't know" error, instead of a false-positive guess (green checkbox).

**Comment by philipbrembeck** [comment]
Script to get vegan ingredients: https://github.com/frontendnetwork/Vegan-Ingredients-Extractor

**Comment by philipbrembeck** [comment]
Rolled out and closed.

**Comment by maltfield** [comment]
unfortunately I cannot confirm due to a TLS error :(

```
user@host:~$ curl -i https://vegancheck.me/
curl: (35) OpenSSL/3.0.14: error:0A000438:SSL routines::tlsv1 alert internal error
user@host:~$ 
```

**Comment by philipbrembeck** [comment]
@maltfield  We changed our url to https://veganify.app due to legal issues 😊 Hope this helps!
